### ISSUE TITLE
Konami code: vidéo indisponible

### ISSUE THREAD

**Issue by adrien-s** [bronycub/v2#21]
Depuis un certain temps (je n'ai l'info que ce soir) la vidéo affichée lors du konami code n'est plus disponible.

À la place, on a simplement un cadre youtube disant « Cette vidéo n'est pas disponible ».

Quelqu'un aurait une copie du fichier d'origine pour la réuploader quelque part ?

cc @heuzef

![](http://files.art-software.fr/index.php?f=15a7237581a8ce)

**Comment by adrien-s** [comment]
Bonne question, y'aurait probablement moyen de coller un fichier en .webm sur le serveur web directement et de mettre un <video> au lieu d'un iframe youtube (ça serait même carrément mieux).

**Comment by heuzef** [comment]
@adrien-s  @Funstenolf  =>  https://gitlab.com/mdevlamynck/sugarcub/issues/78
